{{- if .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-init
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.initJob.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: nominatim
    app.kubernetes.io/component: nominatim
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.initJob.annotations "context" $ ) | nindent 4 }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.initJob.backoffLimit }}
  template:
    metadata:
      {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.initJob.podLabels .Values.commonLabels $versionLabel ) "context" . ) }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/part-of: nominatim
        app.kubernetes.io/component: nominatim
      {{- if .Values.initJob.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.initJob.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        fsGroup: 2000
      initContainers:
        - name: wait-for-db
          image: willwill/wait-for-it
          args:
            - {{ include "nominatim.databaseHost" . }}:{{ include "nominatim.databasePort" . }}

{{- if .Values.initJob.customStyleUrl }}
        - name: download-custom-style
          image: curlimages/curl
          workingDir: /nominatim
          volumeMounts:
            - mountPath: /nominatim
              name: data
          command:
            - curl
            - -A {{ include "chart.userAgent" . }}
            - {{ .Values.initJob.customStyleUrl }}
            - -L
            - -f
            - -o
            - custom.style
{{- end }}

{{- if .Values.initJob.importWikipedia }}
        - name: download-wikipedia
          image: curlimages/curl
          workingDir: /nominatim
          volumeMounts:
            - mountPath: /nominatim
              name: data
          command:
            - curl
            - -A {{ include "chart.userAgent" . }}
            - {{ .Values.initJob.wikipediaUrl }}
            - -L
            - -f
            - -o
            - wikimedia-importance.sql.gz
{{- end }}

{{- if .Values.initJob.importGB_Postcode }}
        - name: download-gb-postcode
          image: curlimages/curl
          workingDir: /nominatim
          volumeMounts:
            - mountPath: /nominatim
              name: data
          command:
            - curl
            - -A {{ include "chart.userAgent" . }}
            - https://www.nominatim.org/data/gb_postcodes.csv.gz
            - -L
            - -f
            - -o
            - gb_postcodes.csv.gz
{{- end }}

{{- if .Values.initJob.importUS_Postcode }}
        - name: download-us-postcode
          image: curlimages/curl
          workingDir: /nominatim
          volumeMounts:
            - mountPath: /nominatim
              name: data
          command:
            - curl
            - -A {{ include "chart.userAgent" . }}
            - https://www.nominatim.org/data/us_postcodes.csv.gz
            - -L
            - -f
            - -o
            - us_postcodes.csv.gz
{{- end }}

        - name: download-pbf
          image: curlimages/curl
          workingDir: /nominatim
          volumeMounts:
            - mountPath: /nominatim
              name: data
          command:
            - /bin/sh
            - -c
            - |
              if [ -f "data.osm.pbf" ]; then
                echo "data.osm.pbf exists."
              else
                echo "Downloading pbf file"
                curl -A {{ include "chart.userAgent" . }} \
                {{ .Values.initJob.pbfUrl }} \
                --create-dirs -L -f -o data.osm.pbf
              fi


      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          workingDir: /nominatim
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.initJob.customStyleUrl }}
            - name: NOMINATIM_IMPORT_STYLE
              value: /nominatim/custom.style
            {{- else }}
            - name: NOMINATIM_IMPORT_STYLE
              value: {{ .Values.initJob.importStyle }}
            {{- end }}
            - name: NOMINATIM_DATABASE_DSN
              {{- if .Values.externalDatabase.existingSecretDsn }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecretDsn }}
                  key: {{ .Values.externalDatabase.existingSecretDsnKey }}
              {{- end }}
              {{- if not .Values.externalDatabase.existingSecretDsn }}
              value: {{ include "nominatim.databaseUrl" . }}
              {{- end }}
            {{- if .Values.flatnode.enabled }}
            - name: NOMINATIM_FLATNODE_FILE
              value: /nominatim/flatnode/flatnode.file
            {{- end }}
            - name: REPLICATION_ENABLED
              value: {{ .Values.updates.enabled | quote }}
            - name: THREADS
              value: {{ .Values.initJob.threads | quote }}
            - name: NOMINATIM_DATABASE_WEBUSER
              value: {{ include "nominatim.databaseUser" . }}
          command:
            - /bin/bash
            - -ec
            - |
              nominatim import --osm-file data.osm.pbf --threads $THREADS
              nominatim index --threads $THREADS
              nominatim admin --check-database

              if [ "$REPLICATION_ENABLED" = "true" ]; then
                nominatim replication --init
                if [ "$FREEZE" = "true" ]; then
                  echo "Skipping freeze because REPLICATION_URL is not empty"
                fi
              else
               if [ "$FREEZE" = "true" ]; then
                  echo "Freezing database"
                  nominatim freeze
                fi
              fi;

              echo "Import job done. Warming up database indices."

              nominatim admin --warm

              echo "Warming finished."
              echo "Initialization finished. Please continue with step 2 now."

          volumeMounts:
            - mountPath: /nominatim
              name: data
            - mountPath: /dev/shm
              name: dshm
            {{- if .Values.flatnode.enabled }}
            - mountPath: /nominatim/flatnode
              name: flatnode
              subPath: flatnode
            {{- end }}
          {{- if .Values.initJob.resources }}
          resources:
            {{- toYaml .Values.initJob.resources | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if  .Values.flatnode.enabled }}
        - name: flatnode
          persistentVolumeClaim:
            claimName: {{ include "common.names.fullname" . }}
        {{- end }}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          {{- if .Values.initJob.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.initJob.persistence.existingClaim | default (printf "%s-data" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-") }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
