apiVersion: v2
name: kimai2
description: A Helm chart for Kubernetes
type: application
version: 4.0.2
appVersion: "apache-2.16.1-prod"

dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
